// INFO phonetic must be an array
// INFO keySegment is transformed into a regex

// INFO base path set to root directory when build
export const fr_paths = {
  fr_words_txt: "./files/fr_words.txt",
  fr_idioms_txt: "./files/fr_idioms.txt",
};

export const searchedPhonetics = [
  {
    word: "Hair",
    phonetic: ["ɛr", "ɛɾ"],
    keySegment: ["air", "èr", "err", "êr", "ert", "er\b"],
  },
  { word: "Chauve", phonetic: ["ʃovə"], keySegment: ["chauve"] },
  { word: "Tif", phonetic: ["tif"], keySegment: ["tif"] },
  { word: "Coupe", phonetic: ["kupə"], keySegment: ["coupe"] },
  { word: "Épi", phonetic: ["epi"], keySegment: ["épi", "aipi"] },
  { word: "Laque", phonetic: ["lakə"], keySegment: ["laque", "lac"] },
  { word: "Mèche", phonetic: ["mɛʃə"], keySegment: ["mèche"] },
  { word: "Coif", phonetic: ["kwaf"], keySegment: ["coif"] },
  { word: "Blonde", phonetic: ["blõdə"], keySegment: ["blonde"] },
  { word: "Brune", phonetic: ["bɾynə"], keySegment: ["brune"] },
  { word: "Brun", phonetic: ["bɾœ̃"], keySegment: ["brun", "brin", "brain"] },
  { word: "Roux", phonetic: ["ru"], keySegment: ["rou"] },
];

export const arrayOfTerminations = [
  "es",
  "ez",
  "ent",
  "ais",
  "ait",
  "ions",
  "iez",
  "aient",
  "erai",
  "eras",
  "era",
  "erons",
  "erez",
  "eront",
  "ai",
  "as",
  "âmes",
  "âtes",
  "èrent",
  "asse",
  "asses",
  "ât",
  "assions",
  "assiez",
  "assent",
  "erais",
  "erait",
  "erions",
  "eriez",
  "eraient",
  "ant",
  "é",
  "és",
  "ée",
  "ées",
  "is",
  "it",
  "issons",
  "issez",
  "issent",
  "issais",
  "issait",
  "issions",
  "issiez",
  "issaient",
  "irai",
  "iras",
  "ira",
  "irons",
  "irez",
  "iront",
  "is",
  "it",
  "îmes",
  "îtes",
  "irent",
  "isse",
  "isses",
  "issions",
  "issiez",
  "issent",
  "ît",
  "irais",
  "irait",
  "irions",
  "iriez",
  "iraient",
  "issons",
  "issez",
  "ue",
  "ues",
  "us",
  "u",
  "ra",
  "na",
  "nât",
  "va",
  "vât",
  "lie",
  "ya",
  "yante",
  "dons",
  "rons",
  "tie",
  "gea",
  "geons",
  "vons",
  "ita",
  "rba",
  "out",
  "enons",
  "drons",
  "dront",
  "tiens",
  "tins",
  "tint",
  "tînt",
  "usa",
  "usons",
  "bla",
  "éda",
  "édons",
  "rons",
  "pta",
  "ptons",
  "ama",
  "amons",
  "imata",
  "imatons",
  "moda",
  "modons",
  "pli",
  "plie",
  "rda",
  "rdons",
  "ha",
  "hons",
  "ût",
  "rdi",
  "rdie",
  "qua",
  "quons",
  "êti",
  "îma",
  "îmons",
  "oli",
  "onda",
  "outi",
  "outons",
  "fia",
  "fa",
  "fions",
  "isa",
  "fie",
  "rri",
  "nuons",
  "rie",
  "rront",
  "bi",
  "gua",
  "guons",
  "oua",
  "ouons",
  "otons",
  "ota",
  "rut",
  "isons",
  "illa",
  "illons",
  "cta",
  "ctons",
  "ssa",
  "ssons",
];
